# Default values for byzer-notebook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

notebook:
  port: 9002
  security.key: abcdefabc3
  user.home: /byzer
  mlsql.engine-url: http://localhost:9003
  mlsql.auth-client: streaming.dsl.auth.client.DefaultConsoleClient
  job.history.max-size: 2000
  job.history.max-time: 30
## Supports DolphinScheduler only    
  scheduler.enable: false
  scheduler.scheduler-url: http://localhost:12345/dolphinscheduler
  scheduler.auth-token: abcdefghijklmn
## MySQL only
  database.port: 3306
  database.name: notebook_flag
  database.ip: "localhost"
  database.username: "changeme"
  database.password: "changeme"

replicaCount: 1
minReadySeconds: 30

image:
  repository: byzer/byzer-notebook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "byzer"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9002

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m    
  tls: []
  #  - secretName: chart-example-tls
  hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
