mode:
  production

###############datasource config##################
#mysql,mongodb,redis等数据源配置方式
production:
  datasources:
    mysql:
      host: 127.0.0.1
      port: 3306
      database: mlsql_console
      username: root
      password: mlsql
      disable: false
      initialSize: 3
      removeAbandoned: true
      testWhileIdle: true
      removeAbandonedTimeout: 30
      filters: stat,log4j
      maxWait: 100

    mongodb:
      disable: true
    redis:
      disable: true

###############application config##################
#'model' for relational database  like MySQL
#'document' for NoSQL database model configuration,  MongoDB
auth_secret: "mlsql"
application:
  controller: tech.mlsql.api.controller
  model:      tech.mlsql.model
  test:       test.com.example
  static:
    enable: true
  template:
    engine:
      enable: true

serviceframework:
  template:
    loader:
      classpath:
        enable: true
  static:
    loader:
      classpath:
        enable: true
        dir: "streamingpro/assets"
###############http config##################
http:
  port: 9002
  disable: false
  host: 0.0.0.0
  client:
    accept:
      timeout: 43200000

###############validator config##################
#如果需要添加验证器，只要配置好类全名即可
#替换验证器实现，则替换相应的类名即可
#warning: 自定义验证器实现需要线程安全

validator:
  format:        net.csdn.validate.impl.Format
  numericality:  net.csdn.validate.impl.Numericality
  presence:      net.csdn.validate.impl.Presence
  uniqueness:    net.csdn.validate.impl.Uniqueness
  length:        net.csdn.validate.impl.Length
  associated:    net.csdn.validate.impl.Associated

mongo_validator:
  format:        net.csdn.mongo.validate.impl.Format
  numericality:  net.csdn.mongo.validate.impl.Numericality
  presence:      net.csdn.mongo.validate.impl.Presence
  uniqueness:    net.csdn.mongo.validate.impl.Uniqueness
  length:        net.csdn.mongo.validate.impl.Length
  associated:    net.csdn.mongo.validate.impl.Associated

################ 数据库类型映射 ####################
type_mapping:  net.csdn.jpa.type.impl.MysqlType

qps:
  /say/hello: 10

qpslimit:
  enable: true
dubbo:
  disable: true
  server: true
