version: "3"
services:
  mysql:
    restart: on-failure
    image: "byzer/mysql:8.0-20.04_beta"
    container_name: "mysql_8.0-20.04_beta"
    ports:
      - 3306:${MYSQL_PORT:-3306}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_ROOT_HOST=%
    networks:
      - byzer-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 2s
      timeout: 180s
      retries: 300
      start_period: 60s
    security_opt:
      - seccomp:unconfined

  byzer-lang:
    image: "byzer/byzer-lang:${SPARK_VERSION:-3.1.1}-${KOLO_LANG_VERSION:-2.2.0-SNAPSHOT}"
    container_name: "byzer-lang_${SPARK_VERSION:-3.1.1}-${KOLO_LANG_VERSION:-2.2.0-SNAPSHOT}"
    restart: on-failure
    networks:
      - byzer-network
    expose:
      - 9003
    ports:
      - 9003:${KOLO_LANG_PORT:-9003}
    healthcheck:
      test: [ "CMD","curl", "-f", "http://127.0.0.1:9003" ]
      interval: 2s
      timeout: 180s
      retries: 300
      start_period: 120s

  byzer-notebook:
    image: "byzer/byzer-notebook:${BYZER_NOTEBOOK_VERSION:-0.0.1-SNAPSHOT}"
    container_name: "byzer-notebook_${BYZER_NOTEBOOK_VERSION:-0.0.1-SNAPSHOT}"
    restart: on-failure
    networks:
      - byzer-network
    depends_on:
      mysql:
        condition: service_healthy
      byzer-lang:
        condition: service_healthy
    ports:
      - 9002:${BYZER_NOTEBOOK_PORT:-9002}

networks:
  byzer-network:
    driver: bridge