version: "3"
services:
  mysql:
    restart: always
    image: "byzer/mysql:8.0-20.04_beta"
    container_name: "mysql_8.0-20.04_beta"
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_ROOT_HOST=%
    networks:
      - byzer-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 2s
      timeout: 180s
      retries: 300
      start_period: 60s
    security_opt:
      - seccomp:unconfined

  byzer-lang:
    image: "byzer/byzer-lang:${SPARK_VERSION:-3.1.1}-${KOLO_LANG_VERSION:-latest}"
    container_name: "byzer-lang_${SPARK_VERSION:-3.1.1}-${KOLO_LANG_VERSION:-latest}"
    restart: always
    networks:
      - byzer-network
    expose:
      - 9003
    ports:
      - ${KOLO_LANG_PORT:-9003}:9003
      - ${SPARK_UI_PORT:-14040}:4040
      - ${YARN_UI_PORT:-18088}:8088
      - ${RAY_DASHBOARD_PORT:-18265}:8265
    healthcheck:
      test: [ "CMD","curl", "-f", "http://127.0.0.1:9003" ]
      interval: 2s
      timeout: 180s
      retries: 300
      start_period: 120s

  byzer-notebook:
    image: "byzer/byzer-notebook:${BYZER_NOTEBOOK_VERSION:-latest}"
    container_name: "byzer-notebook_${BYZER_NOTEBOOK_VERSION:-latest}"
    restart: always
    networks:
      - byzer-network
    depends_on:
      mysql:
        condition: service_healthy
      byzer-lang:
        condition: service_healthy
    ports:
      - ${BYZER_NOTEBOOK_PORT:-9002}:9002

networks:
  byzer-network:
    driver: bridge